name: nextstrain
channels:
- bioconda
- defaults
dependencies:
- cvxopt
- datrie
- fasttree
- iqtree
- mafft
- opencv
- pandas
- psutil
- python=3.6*
- nodejs=10
- raxml
- vcftools
- git
- pip
- pip:
  - nextstrain-augur
  - nextstrain-cli
  - rethinkdb==2.3.0.post6
